export default {
  DX_BOOKMARK_IMAGE_RATIO: 'DX_BOOKMARK_IMAGE_RATIO',

  DX_BOOKMARK_INPUT_CHANGE: 'DX_BOOKMARK_INPUT_CHANGE',
  DX_BOOKMARK_SEARCH_TOGGLE: 'DX_BOOKMARK_SEARCH_TOGGLE',

  DX_ADD_BOOKMARK_REQUEST: 'DX_ADD_BOOKMARK_REQUEST',
  DX_ADD_BOOKMARK_CARDS_SUCCESS: 'DX_ADD_BOOKMARK_CARDS_SUCCESS',
  DX_ADD_BOOKMARK_SECTIONS_SUCCESS: 'DX_ADD_BOOKMARK_SECTIONS_SUCCESS',
  DX_ADD_BOOKMARK_ERRORS: 'DX_ADD_BOOKMARK_ERRORS',

  DX_DELETE_BOOKMARK_REQUEST: 'DX_DELETE_BOOKMARK_REQUEST',
  DX_DELETE_BOOKMARK_SECTIONS_SUCCESS: 'DX_DELETE_BOOKMARK_SECTIONS_SUCCESS',
  DX_DELETE_BOOKMARK_CARDS_SUCCESS: 'DX_DELETE_BOOKMARK_CARDS_SUCCESS',
  DX_DELETE_BOOKMARK_ERRORS: 'DX_DELETE_BOOKMARK_ERRORS',

  DX_GET_BOOKMARKS_CARDS_REQUEST: 'DX_GET_BOOKMARKS_CARDS_REQUEST',
  DX_GET_BOOKMARKS_CARDS_SUCCESS: 'DX_GET_BOOKMARKS_CARDS_SUCCESS',
  DX_GET_BOOKMARKS_CARDS_ERRORS: 'DX_GET_BOOKMARKS_CARDS_ERRORS',

  DX_GET_BOOKMARKS_SECTION_REQUEST: 'DX_GET_BOOKMARKS_SECTION_REQUEST',
  DX_GET_BOOKMARKS_SECTIONS_SUCCESS: 'DX_GET_BOOKMARKS_SECTIONS_SUCCESS',
  DX_GET_BOOKMARKS_SECTIONS_ERRORS: 'DX_GET_BOOKMARKS_SECTIONS_ERRORS',

  DX_BOOKMARK_ADD_DOWNLOAD_REQUEST: 'DX_BOOKMARK_ADD_DOWNLOAD_REQUEST',
  DX_BOOKMARK_ADD_DOWNLOAD_SUCCESS: 'DX_BOOKMARK_ADD_DOWNLOAD_SUCCESS',
  DX_BOOKMARK_ADD_DOWNLOAD_ERRORS: 'DX_BOOKMARK_ADD_DOWNLOAD_ERRORS',

  DX_POST_BOOKMARK_STREAM_EXPRERIENCE_CARD_INFO_REQUEST: 'DX_POST_BOOKMARK_STREAM_EXPRERIENCE_CARD_INFO_REQUEST',
  DX_POST_BOOKMARK_STREAM_EXPRERIENCE_CARD_INFO_V2_REQUEST: 'DX_POST_BOOKMARK_STREAM_EXPRERIENCE_CARD_INFO_V2_REQUEST',
  DX_POST_BOOKMARK_STREAM_EXPRERIENCE_CARD_AND_PAGE_INFO_SUCCESS: 'DX_POST_BOOKMARK_STREAM_EXPRERIENCE_CARD_AND_PAGE_INFO_SUCCESS',
  DX_POST_BOOKMARK_STREAM_EXPRERIENCE_CARD_ONLY_INFO_SUCCESS: 'DX_POST_BOOKMARK_STREAM_EXPRERIENCE_CARD_ONLY_INFO_SUCCESS',
  DX_POST_BOOKMARK_STREAM_EXPRERIENCE_CARD_INFO_ERRORS: 'DX_POST_BOOKMARK_STREAM_EXPRERIENCE_CARD_INFO_ERRORS',

  DX_BOOKMARK_SKIP_THE_CONTENT_UPDATE_REQUEST: 'DX_BOOKMARK_SKIP_THE_CONTENT_UPDATE_REQUEST',

  DX_OPEN_BOOKMARK_CARDS_PAGE: 'DX_OPEN_BOOKMARK_CARDS_PAGE',
  DX_CLOSE_BOOKMARK_CARDS_PAGE: 'DX_CLOSE_BOOKMARK_CARDS_PAGE',

  DX_OPEN_BOOKMARK_SECTION_PAGE: 'DX_OPEN_BOOKMARK_SECTION_PAGE',
  DX_CLOSE_BOOKMARK_SECTION_PAGE: 'DX_CLOSE_BOOKMARK_SECTION_PAGE',

  UPDATE_PAGE_NUMBER_BOOKMARKS: 'UPDATE_PAGE_NUMBER_BOOKMARKS',
};
