export default {
  DX_VIDEO_SCREEN: 'DX_VIDEO_SCREEN',
  DX_VIDEO_SCREEN_CLOSE: 'DX_VIDEO_SCREEN_CLOSE',
  DX_VIDEO_SCREEN_CARD_ONLY_CLOSE_REQUEST: 'DX_VIDEO_SCREEN_CARD_ONLY_CLOSE_REQUEST',
  DX_VIDEO_SCREEN_CARD_ONLY_CLOSE_SUCCESS: 'DX_VIDEO_SCREEN_CARD_ONLY_CLOSE_SUCCESS',
  DX_VIDEO_SCREEN_CARD_ONLY_CLOSE_ERRORS: 'DX_VIDEO_SCREEN_CARD_ONLY_CLOSE_ERRORS',

  DX_OPEN_TAGS_LIST_VIEW_PAGE: 'DX_OPEN_TAGS_LIST_VIEW_PAGE',

  GET_USER_PHONE_UNIQUE_ID: 'GET_USER_PHONE_UNIQUE_ID',

  GET_INTERNET_INFO: 'GET_INTERNET_INFO',

  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  CLOSE_CARD_ONLY_MODAL_REQUEST: 'CLOSE_CARD_ONLY_MODAL_REQUEST',
  CLOSE_CARD_ONLY_MODAL_SUCCESS: 'CLOSE_CARD_ONLY_MODAL_SUCCESS',
  CLOSE_CARD_ONLY_MODAL_ERRORS: 'CLOSE_CARD_ONLY_MODAL_ERRORS',

  OPEN_INFO_MODAL: 'OPEN_INFO_MODAL',
  OPEN_LANGUAGE_MODAL: 'OPEN_LANGUAGE_MODAL',

  GET_APP_INFO_REQUEST: 'GET_APP_INFO_REQUEST',
  GET_APP_INFO_SUCCESS: 'GET_APP_INFO_SUCCESS',
  GET_APP_INFO_ERRORS: 'GET_APP_INFO_ERRORS',

  GET_USER_INFO_REQUEST: 'GET_USER_INFO_REQUEST',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_ERRORS: 'GET_USER_INFO_ERRORS',

  GET_APPSTATE: 'GET_APPSTATE',

  SELECT_LANGUAGE_SUCCESS: 'SELECT_LANGUAGE_SUCCESS',

  OPEN_LANGUAGE_PAGE: 'OPEN_LANGUAGE_PAGE',
  CLOSE_LANGUAGE_PAGE: 'CLOSE_LANGUAGE_PAGE',

  SET_APP_LANGUAGE_REQUEST: 'SET_APP_LANGUAGE_REQUEST',
  SET_APP_LANGUAGE_SUCCESS: 'SET_APP_LANGUAGE_SUCCESS',
  SET_APP_LANGUAGE_ERRORS: 'SET_APP_LANGUAGE_ERRORS',

  SET_APP_LANGUAGE_MODAL_REQUEST: 'SET_APP_LANGUAGE_MODAL_REQUEST',
  SET_APP_LANGUAGE_MODAL_SUCCESS: 'SET_APP_LANGUAGE_MODAL_SUCCESS',
  SET_APP_LANGUAGE_MODAL_ERRORS: 'SET_APP_LANGUAGE_MODAL_ERRORS',

  AUTO_SET_LANGUAGE: 'AUTO_SET_LANGUAGE',


  GET_HEARTBEAT_V0_REQUEST: 'GET_HEARTBEAT_V0_REQUEST',
  GET_HEARTBEAT_V0_SUCCESS: 'GET_HEARTBEAT_V0_SUCCESS',
  GET_HEARTBEAT_V0_ERRORS: 'GET_HEARTBEAT_V0_ERRORS',
  GET_HEARTBEAT_V0_VERSION_MISMATCH: 'GET_HEARTBEAT_V0_VERSION_MISMATCH',

  GET_HEARTBEAT_REQUEST: 'GET_HEARTBEAT_REQUEST',
  GET_HEARTBEAT_SUCCESS: 'GET_HEARTBEAT_SUCCESS',
  GET_HEARTBEAT_ERRORS: 'GET_HEARTBEAT_ERRORS',
  GET_HEARTBEAT_VERSION_MISMATCH: 'GET_HEARTBEAT_VERSION_MISMATCH',

  DX_MINIMIZE_APP_REQUEST: 'DX_MINIMIZE_APP_REQUEST',
  DX_MINIMIZE_APP_SUCCESS: 'DX_MINIMIZE_APP_SUCCESS',
  DX_MINIMIZE_APP_ERRORS: 'DX_MINIMIZE_APP_ERRORS',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERRORS: 'LOGIN_ERRORS',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_ERRORS: 'LOGOUT_ERRORS',

  ANONYMOUS_LOGIN_REQUEST: 'ANONYMOUS_LOGIN_REQUEST',
  ANONYMOUS_LOGIN_SUCCESS: 'ANONYMOUS_LOGIN_SUCCESS',
  ANONYMOUS_LOGIN_ERORRS: 'ANONYMOUS_LOGIN_ERORRS',

  DX_REFRESH_TOKEN_UPDATE: 'DX_REFRESH_TOKEN_UPDATE',

  DX_OPEN_HOME_PAGE: 'DX_OPEN_HOME_PAGE',
  DX_OPEN_EXPLORE_PAGE: 'DX_OPEN_EXPLORE_PAGE',
  DX_OPEN_BOOKMARK_PAGE: 'DX_OPEN_BOOKMARK_PAGE',

  OPEN_EMBEDDED_LINK_MODAL: 'OPEN_EMBEDDED_LINK_MODAL',
  CLOSE_EMBEDDED_LINK_MODAL: 'CLOSE_EMBEDDED_LINK_MODAL',

  // Load first flow
  GET_FIRST_LOAD_REQUEST: 'GET_FIRST_LOAD_REQUEST',
  GET_FIRST_LOAD_SUCCESS: 'GET_FIRST_LOAD_SUCCESS',
  GET_FIRST_LOAD_ERRORS: 'GET_FIRST_LOAD_ERRORS',

  CLOSE_AUDIO_MODAL: "CLOSE_AUDIO_MODAL",
};
