export default {
  DX_FEATURED_PAGE_OPEN: 'DX_FEATURED_PAGE_OPEN',
  DX_FEATURED_PAGE_CLOSE: 'DX_FEATURED_PAGE_CLOSE',

  DX_MOST_POPULAR_PAGE_OPEN: 'DX_MOST_POPULAR_PAGE_OPEN',
  DX_MOST_POPULAR_PAGE_CLOSE: 'DX_MOST_POPULAR_PAGE_CLOSE',

  DX_NEW_RELEASES_PAGE_OPEN: 'DX_NEW_RELEASES_PAGE_OPEN',
  DX_NEW_RELEASES_PAGE_CLOSE: 'DX_NEW_RELEASES_PAGE_CLOSE',

  DX_TRENDING_PAGE_OPEN: 'DX_TRENDING_PAGE_OPEN',
  DX_TRENDING_PAGE_CLOSE: 'DX_TRENDING_PAGE_CLOSE',


  DX_UPDATE_PAGE_NUMBER: 'DX_UPDATE_PAGE_NUMBER',
};
