export default {
  DX_HOME_IMAGE_RATIO: 'DX_HOME_IMAGE_RATIO',

  DX_UPDATE_MY_CHANNELS_LIST_PAGE_NUMBER: "DX_UPDATE_MY_CHANNELS_LIST_PAGE_NUMBER",

  // Search Download Cards
  DX_GET_DOWNLOAD_CARDS: 'DX_GET_DOWNLOAD_CARDS',

  // Get Featured Cards
  DX_GET_FEATURED_CARDS_REQUEST: 'DX_GET_FEATURED_CARDS_REQUEST',
  DX_GET_FEATURED_CARDS_SUCCESS: 'DX_GET_FEATURED_CARDS_SUCCESS',
  DX_GET_FEATURED_CARDS_ERRORS: 'DX_GET_FEATURED_CARDS_ERRORS',

  // Get Featured Cards
  DX_GET_MOST_POPULAR_CARDS_REQUEST: 'DX_GET_MOST_POPULAR_CARDS_REQUEST',
  DX_GET_MOST_POPULAR_CARDS_SUCCESS: 'DX_GET_MOST_POPULAR_CARDS_SUCCESS',
  DX_GET_MOST_POPULAR_CARDS_ERRORS: 'DX_GET_MOST_POPULAR_CARDS_ERRORS',

  // Get Featured Cards
  DX_GET_NEW_RELEASES_CARDS_REQUEST: 'DX_GET_NEW_RELEASES_CARDS_REQUEST',
  DX_GET_NEW_RELEASES_CARDS_SUCCESS: 'DX_GET_NEW_RELEASES_CARDS_SUCCESS',
  DX_GET_NEW_RELEASES_CARDS_ERRORS: 'DX_GET_NEW_RELEASES_CARDS_ERRORS',

  // Get Featured Cards
  DX_GET_TRENDING_CARDS_REQUEST: 'DX_GET_TRENDING_CARDS_REQUEST',
  DX_GET_TRENDING_CARDS_SUCCESS: 'DX_GET_TRENDING_CARDS_SUCCESS',
  DX_GET_TRENDING_CARDS_ERRORS: 'DX_GET_TRENDING_CARDS_ERRORS',

  // Get My channels
  DX_GET_MY_CHANNELS_LIST_REQUEST: 'DX_GET_MY_CHANNELS_LIST_REQUEST',
  DX_GET_MY_CHANNELS_LIST_SUCCESS: 'DX_GET_MY_CHANNELS_LIST_SUCCESS',
  DX_GET_MY_CHANNELS_LIST_ERRORS: 'DX_GET_MY_CHANNELS_LIST_ERRORS',

  DX_MY_CHANNELS_BACK:'DX_MY_CHANNELS_BACK',

};
