export default {
  DX_POST_CHANNEL_LIST_REQUEST: 'DX_POST_CHANNEL_LIST_REQUEST',
  DX_POST_CHANNEL_LIST_SUCCESS: 'DX_POST_CHANNEL_LIST_SUCCESS',
  DX_CHANNELS_ERRORS: 'DX_CHANNELS_ERRORS',

  DX_POST_CHANNEL_SUBSCRIBE_REQUEST: 'DX_POST_CHANNEL_SUBSCRIBE_REQUEST',
  DX_POST_CHANNEL_SUBSCRIBE_SUCCESS: 'DX_POST_CHANNEL_SUBSCRIBE_SUCCESS',
  DX_POST_CHANNEL_SUBSCRIBE_FAILURE: 'DX_POST_CHANNEL_SUBSCRIBE_FAILURE',

  DX_POST_SUBSCRIBE_INVITE_CHANNEL_REQUEST: 'DX_POST_SUBSCRIBE_INVITE_CHANNEL_REQUEST',
  DX_POST_SUBSCRIBE_INVITE_CHANNEL_SUCCESS: 'DX_POST_SUBSCRIBE_INVITE_CHANNEL_SUCCESS',
  DX_POST_SUBSCRIBE_INVITE_CHANNEL_ERRORS: 'DX_POST_SUBSCRIBE_INVITE_CHANNEL_ERRORS',

  DX_OPEN_PROMO_BUTTON_CONSENT_ON_SEARCH_CLICK: 'DX_OPEN_PROMO_BUTTON_CONSENT_ON_SEARCH_CLICK',
  DX_CLOSE_PROMO_BUTTON_CONSENT_ON_SEARCH_CLICK: 'DX_CLOSE_PROMO_BUTTON_CONSENT_ON_SEARCH_CLICK',

  UPDATE_PAGE_NUMBER_CHANNEL: 'UPDATE_PAGE_NUMBER_CHANNEL',

  DX_OPEN_CLICKED_CHANNEL_EXPERIENCES: 'DX_OPEN_CLICKED_CHANNEL_EXPERIENCES',
  DX_OPEN_CLICKED_CHANNEL_EXPERIENCES_V2: 'DX_OPEN_CLICKED_CHANNEL_EXPERIENCES_V2',
};
