export default {
  DX_REGISTER_REQUEST: 'DX_REGISTER_REQUEST',
  DX_REGISTER_SUCCESS: 'DX_REGISTER_SUCCESS',
  DX_REGISTER_ERRORS: 'DX_REGISTER_ERRORS',

  OPEN_REGISTER_PAGE: 'OPEN_REGISTER_PAGE',
  CLOSE_REGISTER_PAGE: 'CLOSE_REGISTER_PAGE',

  UPDATE_REGISTER_INPUT: 'UPDATE_REGISTER_INPUT',

  DX_EMAIL_CHECK_REQUEST: 'DX_EMAIL_CHECK_REQUEST',
  DX_EMAIL_CHECK_SUCCESS: 'DX_EMAIL_CHECK_SUCCESS',
  DX_EMAIL_CHECK_ERRORS: 'DX_EMAIL_CHECK_ERRORS',
};
