export default {

  DX_DOWNLOAD_PAGE_OPEN: 'DX_DOWNLOAD_PAGE_OPEN',
  DX_DOWNLOAD_PAGE_CLOSE: 'DX_DOWNLOAD_PAGE_CLOSE',

  DX_DOWNLOAD_IMAGE_RATIO: 'DX_DOWNLOAD_IMAGE_RATIO',

  DX_DELETE_DOWNLOAD_REQUEST: 'DX_DELETE_DOWNLOAD_REQUEST',
  DX_DELETE_DOWNLOAD_SUCCESS: 'DX_DELETE_DOWNLOAD_SUCCESS',
  DX_DELETE_DOWNLOAD_ERRORS: 'DX_DELETE_DOWNLOAD_ERRORS',

  DX_CLEAR_DOWNLOAD_REQUEST: 'DX_CLEAR_DOWNLOAD_REQUEST',
  DX_CLEAR_DOWNLOAD_SUCCESS: 'DX_CLEAR_DOWNLOAD_SUCCESS',
  DX_CLEAR_DOWNLOAD_ERRORS: 'DX_CLEAR_DOWNLOAD_ERRORS',

  DX_GET_DOWNLOADS_DIRECTORY_REQUEST: 'DX_GET_DOWNLOADS_DIRECTORY_REQUEST',
  DX_GET_DOWNLOADS_DIRECTORY_SUCCESS: 'DX_GET_DOWNLOADS_DIRECTORY_SUCCESS',
  DX_GET_DOWNLOADS_DIRECTORY_ERRORS: 'DX_GET_DOWNLOADS_DIRECTORY_ERRORS',

  UPDATE_PAGE_NUMBER_DONWLOADS: 'UPDATE_PAGE_NUMBER_DONWLOADS',
  DX_DOWNLOAD_INPUT_CHANGE: 'DX_DOWNLOAD_INPUT_CHANGE',
};
