export default {

  DX_FEED_CHANNEL_CHANGE: 'DX_FEED_CHANNEL_CHANGE',
  DX_BROWSE_TO_PREVIOUS_TAB: 'DX_BROWSE_TO_PREVIOUS_TAB',

  DX_SCROLL: 'DX_SCROLL',

  DX_ARCHIVE: 'DX_ARCHIVE',
  DX_ARCHIVE_SUCCESS: 'DX_ARCHIVE_SUCCESS',
  DX_ARCHIVE_ERRORS: 'DX_ARCHIVE_ERRORS',

  DX_FEED_BACK: 'DX_FEED_BACK',
  DX_FEED_BACK_SUCCESS: 'DX_FEED_BACK_SUCCESS',
  DX_FEED_BACK_ERRORS: 'DX_FEED_BACK_ERRORS',

  DX_FEED_BACK_COMPLETE: 'DX_FEED_BACK_COMPLETE',
  DX_FEED_BACK_COMPLETE_SUCCESS: 'DX_FEED_BACK_COMPLETE_SUCCESS',
  DX_FEED_BACK_COMPLETE_ERRORS: 'DX_FEED_BACK_COMPLETE_ERRORS',

  DX_BROWSER: 'DX_BROWSER',

  DX_BROWSER_BACK: 'DX_BROWSER_BACK',
  DX_BROWSER_BACK_SUCCESS: 'DX_BROWSER_BACK_SUCCESS',
  DX_BROWSER_BACK_ERRORS: 'DX_BROWSER_BACK_ERRORS',

  DX_HOME_BROWSER_BACK: 'DX_HOME_BROWSER_BACK',
  DX_HOME_BROWSER_BACK_SUCCESS: 'DX_HOME_BROWSER_BACK_SUCCESS',
  DX_HOME_BROWSER_BACK_ERRORS: 'DX_HOME_BROWSER_BACK_ERRORS',

  DX_HOME_BACK: 'DX_HOME_BACK',
  DX_HOME_BACK_SUCCESS: 'DX_HOME_BACK_SUCCESS',
  DX_HOME_BACK_ERRORS: 'DX_HOME_BACK_ERRORS',

  DX_SECTION_MENU_TOGGLE: 'DX_SECTION_MENU_TOGGLE',

  DX_SECTION_BROWSER: 'DX_SECTION_BROWSER',
  DX_SECTION_BROWSER_BACK: 'DX_SECTION_BROWSER_BACK',
  DX_SECTION_SUGGEST_BROWSER: 'DX_SECTION_SUGGEST_BROWSER',

  DX_ADD_BOOKMARK: 'DX_ADD_BOOKMARK',
  DX_BROWSE_TO_SECTION_PAGE: 'DX_BROWSE_TO_SECTION_PAGE',
  DX_BROWSE_TO_CHANNEL_PAGE: 'DX_BROWSE_TO_CHANNEL_PAGE',

  DX_POST_STREAM_EXPRERIENCE_LIST_REQUEST: 'DX_POST_STREAM_EXPRERIENCE_LIST_REQUEST',
  DX_POST_STREAM_EXPRERIENCE_LIST_SUCCESS: 'DX_POST_STREAM_EXPRERIENCE_LIST_SUCCESS',
  DX_POST_STREAM_EXPRERIENCE_LIST_ERRORS: 'DX_POST_STREAM_EXPRERIENCE_LIST_ERRORS',


  DX_POST_STREAM_EXPRERIENCE_CARD_INFO_REQUEST: 'DX_POST_STREAM_EXPRERIENCE_CARD_INFO_REQUEST',
  DX_POST_STREAM_EXPRERIENCE_CARD_INFO_V2_REQUEST: 'DX_POST_STREAM_EXPRERIENCE_CARD_INFO_V2_REQUEST',
  DX_POST_STREAM_EXPRERIENCE_CARD_AND_PAGE_INFO_SUCCESS: 'DX_POST_STREAM_EXPRERIENCE_CARD_AND_PAGE_INFO_SUCCESS',
  DX_POST_STREAM_EXPRERIENCE_CARD_ONLY_INFO_SUCCESS: 'DX_POST_STREAM_EXPRERIENCE_CARD_ONLY_INFO_SUCCESS',
  DX_POST_STREAM_EXPRERIENCE_CARD_INFO_ERRORS: 'DX_POST_STREAM_EXPRERIENCE_CARD_INFO_ERRORS',

  DX_ADD_DOWNLOAD_REQUEST: 'DX_ADD_DOWNLOAD_REQUEST',
  DX_ADD_DOWNLOAD_SUCCESS: 'DX_ADD_DOWNLOAD_SUCCESS',
  DX_ADD_DOWNLOAD_ERRORS: 'DX_ADD_DOWNLOAD_ERRORS',


  POST_FEEDBACK: 'POST_FEEDBACK',

  DX_OPEN_UPDATE_USER_SYNC_MODAL: 'DX_OPEN_UPDATE_USER_SYNC_MODAL',
  DX_UPDATE_USER_THE_CONTENT_REQUEST: 'DX_UPDATE_USER_THE_CONTENT_REQUEST',
  
  DX_OPEN_UPDATE_USER_CONSENT_MODAL: 'DX_OPEN_UPDATE_USER_CONSENT_MODAL',
  DX_SKIP_THE_CONTENT_UPDATE_REQUEST: 'DX_SKIP_THE_CONTENT_UPDATE_REQUEST',

  SET_RESET_ARCHIVE: 'SET_RESET_ARCHIVE',

  UPDATE_PAGE_NUMBER: 'UPDATE_PAGE_NUMBER',

  UPDATE_SECTION_PAGE_NUMBER: 'UPDATE_SECTION_PAGE_NUMBER',

  DX_TRAINING_COMPLETE: 'DX_TRAINING_COMPLETE',
  DX_TRAINING_COMPLETE_SUCCESS: 'DX_TRAINING_COMPLETE_SUCCESS',
  DX_TRAINING_COMPLETE_ERRORS: 'DX_TRAINING_COMPLETE_ERRORS',
};
