export default {

  DX_OPEN_SETTINGS_PAGE: 'DX_OPEN_SETTINGS_PAGE',
  DX_CLOSE_SETTINGS_PAGE: 'DX_CLOSE_SETTINGS_PAGE',

  DX_TOGGLE_NIGHT_MODE_REQUEST: 'DX_TOGGLE_NIGHT_MODE_REQUEST',
  DX_TOGGLE_NIGHT_MODE_SUCCESS: 'DX_TOGGLE_NIGHT_MODE_SUCCESS',
  DX_TOGGLE_NIGHT_MODE_ERORRS: 'DX_TOGGLE_NIGHT_MODE_ERORRS',
};
