export default {
  DX_INPUT_CHANGE: 'DX_INPUT_CHANGE',
  DX_SECTION_INPUT_CHANGE: 'DX_SECTION_INPUT_CHANGE',
  DX_SEARCH_TOGGLE: 'DX_SEARCH_TOGGLE',
  DX_SEARCH_SECTION_TOGGLE: 'DX_SEARCH_SECTION_TOGGLE',
  DX_HANDLE_CURRENT_TAB: 'DX_HANDLE_CURRENT_TAB',
  DX_UPDATE_CURRENT_SECTION_SEARCH_TAB: 'DX_UPDATE_CURRENT_SECTION_SEARCH_TAB',

  // Get Tags List
  DX_GET_TAGS_LIST_REQUEST: 'DX_GET_TAGS_LIST_REQUEST',
  DX_GET_TAGS_LIST_SUCCESS: 'DX_GET_TAGS_LIST_SUCCESS',
  DX_GET_TAGS_LIST_ERRORS: 'DX_GET_TAGS_LIST_ERRORS',

  DX_UPDATE_TAGS_LIST_PAGE_NUMBER: 'DX_UPDATE_TAGS_LIST_PAGE_NUMBER',

  // Get Channels List
  DX_GET_CHANNELS_LIST_REQUEST: 'DX_GET_CHANNELS_LIST_REQUEST',
  DX_GET_CHANNELS_LIST_SUCCESS: 'DX_GET_CHANNELS_LIST_SUCCESS',
  DX_GET_CHANNELS_LIST_ERRORS: 'DX_GET_CHANNELS_LIST_ERRORS',

  DX_UPDATE_CHANNELS_LIST_PAGE_NUMBER:  'DX_UPDATE_CHANNELS_LIST_PAGE_NUMBER',

  // Get Content List
  DX_GET_CONTENT_LIST_REQUEST: 'DX_GET_CONTENT_LIST_REQUEST',
  DX_GET_CONTENT_LIST_SUCCESS: 'DX_GET_CONTENT_LIST_SUCCESS',
  DX_GET_CONTENT_LIST_ERRORS: 'DX_GET_CONTENT_LIST_ERRORS',

  // Tag Exp click
  DX_GET_TAG_EXP_REQUEST: 'DX_GET_TAG_EXP_REQUEST',
  DX_GET_TAG_EXP_SUCCESS: 'DX_GET_TAG_EXP_SUCCESS',
  DX_GET_TAG_EXP_ERRORS: 'DX_GET_TAG_EXP_ERRORS',

  DX_UPDATE_TAG_EXP_LIST_PAGE_NUMBER: 'DX_UPDATE_TAG_EXP_LIST_PAGE_NUMBER',

  DX_UPDATE_CONTENT_LIST_PAGE_NUMBER: 'DX_UPDATE_CONTENT_LIST_PAGE_NUMBER',
  
  DX_UPDATE_SEARCH_SECTION_LIST_PAGE_NUMBER: 'DX_UPDATE_SEARCH_SECTION_LIST_PAGE_NUMBER',

  DX_GET_SEARCH_LIST_REQUEST: 'DX_GET_SEARCH_LIST_REQUEST',
  DX_GET_SEARCH_LIST_SUCCESS: 'DX_GET_SEARCH_LIST_SUCCESS',
  DX_GET_SEARCH_LIST_ERRORS: 'DX_GET_SEARCH_LIST_ERRORS',

  DX_GET_SEARCH_LIST_V2_REQUEST: 'DX_GET_SEARCH_LIST_V2_REQUEST',
  DX_GET_SEARCH_LIST_V2_SUCCESS: 'DX_GET_SEARCH_LIST_V2_SUCCESS',
  DX_GET_SEARCH_LIST_V2_ERRORS: 'DX_GET_SEARCH_LIST_V2_ERRORS',

  DX_HANDLE_GO_TO_PAGE: 'DX_HANDLE_GO_TO_PAGE',
};
